INSERT INTO champion 
VALUES
('Vayne', 'ADC', 'Night Hunter', 'Tumble', 'Silver Bolts', 'Condemn', 'Final Hour', 'Hyper Carry'),
('Aatrox', 'TOP', 'Deathbringer', 'Darkin Dlade', 'Infernal Chains', 'Umbral Dash', 'World Ender', 'Bruiser'),
('Ahri', 'MID', 'Vastayan Grace', 'Orb of Deception', 'Fox-Fire', 'Charm', 'Spirit Rush', 'Mage'),
('Akali', 'MID', 'Assassin Mark', 'Five Point Strike', 'Twilight Shroud', 'Shuriken Flip'. 'Perfect Execution', 'Assassin'),
('Alistar', 'SUP', 'Triumphant Roar', 'Pulverize', 'Headbutt'. 'Trample', 'Unbreakable Will'. 'Tank'),
('Ashe', 'ADC', 'Frost Shot', 'Ramper Focus', 'Volley'. 'Hawkshot', 'Enchanted Arrow'. 'Ranged Carry'),
('Azir', 'MID', 'Shurima Legacy', 'Conquering Sands', 'Arise'. 'Shifting Sands', 'Emperor Divide'. 'Mage'),
('Bard', 'SUP', 'Traveler Call', 'Cosmic Binding', 'Caretaker Shrine'. 'Magical Journey', 'Tempered Fate'. 'Mage'),
('Blitz', 'SUP', 'Mana Barrier', 'Rocket Grab', 'Overdrive'. 'Power Fist', 'Static Field'. 'Bruiser'),
('Braum', 'SUP', 'Concussive Blows', 'Winter Bite', 'Stand Behind Me'. 'Unbreakable', 'Glacial Fissure'. 'Tank'),
('Caitlyn', 'ADC', 'Headshot', 'Peacemaker', 'Yordle Snap Trap'. '90 Caliber net', 'Ace in the Hole'. 'Ranged Carry'),
('Camile', 'TOP', 'Adaptive Defense', 'Precision Protocol', 'Tatical Sweep'. 'Hookshot', 'Hextech Ultimatum'. 'Bruiser'),
('Cassiopeia', 'MID', 'Serpentine Grace', 'Noxious Blast', 'Miasma'. 'Twin Fang', 'Petrifying Gaze'. 'Mage'),
('Diana', 'MID', 'Moonsilver Blade', 'Crescent Strike', 'Pale Cascade'. 'Moonfall', 'Lunar Rush'. 'Assassin'),
('Dr. Mundo', 'TOP', 'Adrenaline Rush', 'Infected Cleaver', 'Burning Agony'. 'Masochism', 'Sadism'. 'Tank'),
('Draven', 'ADC', 'League of Draven', 'Spinning Axe', 'Blood Rush'. 'Stand Aside', 'Whirling Death'. 'Ranged Carry'),
('Ekko', 'JNG', 'Z-Drive', 'Timewinder', 'Parallel Convergence'. 'Phase Dive', 'Chronobreak'. 'Mage'),
('Elise', 'JNG', 'Spider Queen', 'Neurotoxin', 'Volatile Spiderling'. 'Cacoon', 'Spider Form'. 'Assassin'),
('Ezreal', 'ADC', 'Rising Spell Force', 'Mystic Shot', 'Essence Flux'. 'Arcane Shift', 'Trueshot Barrage'. 'Ranged Carry'),
('Fiora', 'TOP', 'Duelist Dance', 'Lunge', 'Riposte'. 'Bladework', 'Grand Challenge'. 'Bruiser'),
('Fizz', 'MID', 'Nimble Fighter', 'Urchin Strike', 'Seastone Trident'. 'Trickster', 'Chum the Waters'. 'Assassin'),
('Galio', 'MID', 'Colossal Smash', 'Winds of War', 'Shield of Durand'. 'Justice Punch', 'Hero Entrance'. 'Tank'),
('Gangplank', 'TOP', 'Trial by Fire', 'Parrley', 'Remove Scurvy'. 'Powder Keg', 'Cannon Barrage'. 'Fighter'),
('Garen', 'TOP', 'Perseverance', 'Decisive Strike', 'Courage'. 'Judgment', 'Demacian Justice'. 'Bruiser'),
('Gragas', 'JNG', 'Happy Hour', 'Barrel Roll', 'Druken Rage'. 'Body Slam', 'Explosive Cask'. 'Bruiser'),
('Graves', 'JNG', 'New Destiny', 'End of the Line', 'Smoke Screen'. 'Quickdraw', 'Collateral Damage'. 'Fighter'),
('Hecarim', 'JNG', 'Warpath', 'Rampage', 'Spirit of Dread'. 'Devastating Charge', 'Onslaught of Shadows'. 'Bruiser'),
('Irelia', 'TOP', 'Ionian Fervor', 'Bladesurge', 'Defiant Dance'. 'Flawless Duet', 'Vanguard Edge'. 'Fighter'),
('Ivern', 'JNG', '', '', ''. '', ''. 'Mage'),
('Janna', 'SUP', '', '', ''. '', ''. 'Mage'),
('Jarvan IV', 'JNG', '', '', ''. '', ''. 'Bruiser'),
('Jax', 'TOP', '', '', ''. '', ''. 'Bruiser'),
('Jayce', 'MID', '', '', ''. '', ''. 'Fighter'),
('Jhin', 'ADC', '', '', ''. '', ''. 'Ranged Carry'),
('Jinx', 'ADC', '', '', ''. '', ''. 'Hyper Carry'),
('Kaisa', 'ADC', '', '', ''. '', ''. 'Ranged Carry'),
('Kalista', 'ADC', '', '', ''. '', ''. 'Ranged Carry'),
('Karma', 'SUP', '', '', ''. '', ''. 'Mage'),
('Kayn', 'JNG', '', '', ''. '', ''. 'Bruiser'),
('Khazix', 'JNG', '', '', ''. '', ''. 'Assassin'),
('Kled', 'TOP', '', '', ''. '', ''. 'Bruiser'),
('Lee Sin', 'JNG', '', '', ''. '', ''. 'Fighter'),
('Lucian', 'ADC', '', '', ''. '', ''. 'Ranged Carry'),
('Lulu', 'SUP', '', '', ''. '', ''. 'Mage'),
('Nami', 'SUP', '', '', ''. '', ''. 'Mage'),
('Nautilus', 'SUP', '', '', ''. '', ''. 'Tank'),
('Nidalee', 'JNG', '', '', ''. '', ''. 'Assassin'),
('Olaf', 'JNG', '', '', ''. '', ''. 'Bruiser'),
('Oriana', 'MID', '', '', ''. '', ''. 'Mage'),
('Ornn', 'TOP', '', '', ''. '', ''. 'Tank'),
('Reksai', 'JNG', '', '', ''. '', ''. 'Bruiser'),
('Rengar', 'JNG', '', '', ''. '', ''. 'Assassin'),
('Shen', 'TOP', '', '', ''. '', ''. 'Bruiser'),
('Singed', 'TOP', '', '', ''. '', ''. 'Tank'),
('Taric', 'SUP', '', '', ''. '', ''. 'Tank'),
('Teemo', 'TOP', '', '', ''. '', ''. 'Mage'),
('Thresh', 'SUP', '', '', ''. '', ''. 'Fighter'),
('Tristana', 'ADC', '', '', ''. '', ''. 'Ranged Carry'),
('Twisted Fate', 'MID', '', '', ''. '', ''. 'Mage'),
('Udyr', 'JNG', '', '', ''. '', ''. 'Bruiser'),
('Vladimir', 'MID', '', '', ''. '', ''. 'Mage'),
('Volibear', 'JNG', 'Chosen of the Storm', 'Rolling Thunder', 'Frenzy', 'Majestic Roar'. 'Thunder Claws', 'Bruiser'),
('Zed', 'MID', 'Condempt Weak', 'Razor Shuriken', 'Living Shadow'. 'Shadow Slash', 'Death Mark'. 'Assassin');
