INSERT INTO play VALUES ('Disable Chat', 'Olaf');
INSERT INTO play VALUES ('Disable Chat', 'Elise');
INSERT INTO play VALUES ('Disable Chat', 'Diana');
INSERT INTO play VALUES ('Disable Chat', 'Vayne');
INSERT INTO play VALUES ('Disable Chat', 'Taric');
INSERT INTO play VALUES ('Faker', 'Oriana');
INSERT INTO play VALUES ('Faker', 'Zed');
INSERT INTO play VALUES ('Faker', 'Lulu');
INSERT INTO play VALUES ('Faker', 'Lucian');
INSERT INTO play VALUES ('Slazlon', 'Blitz');
INSERT INTO play VALUES ('Slazlon', 'Ezreal');
